package gg.amecute.auralithutilities.Multiblock;

import aztech.modern_industrialization.MI;
import aztech.modern_industrialization.MIBlock;
import aztech.modern_industrialization.machines.BEP;
import aztech.modern_industrialization.machines.components.OrientationComponent;
import aztech.modern_industrialization.machines.init.MIMachineRecipeTypes;
import aztech.modern_industrialization.machines.models.MachineCasing;
import aztech.modern_industrialization.machines.models.MachineCasings;
import aztech.modern_industrialization.machines.multiblocks.HatchFlags;
import aztech.modern_industrialization.machines.multiblocks.ShapeTemplate;
import aztech.modern_industrialization.machines.multiblocks.SimpleMember;
import aztech.modern_industrialization.machines.recipe.MachineRecipeType;
import gg.amecute.auralithutilities.Animation.AnimationSystem;
import gg.amecute.auralithutilities.Animation.Impl.BlackHoleCraftingAnim;
import gg.amecute.auralithutilities.AuralithUtilities;
import gg.amecute.auralithutilities.Utils.ShapeFixer;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.Vec3;

import static aztech.modern_industrialization.machines.multiblocks.HatchTypes.*;

public class BlackHoleCrafter extends AuralithMultiblock {

    public BlackHoleCrafter(BEP bep, MachineCasing hatchCasing) {
        super(
                bep,
                ResourceLocation.fromNamespaceAndPath(AuralithUtilities.MODID, "BlackHoleCrafter"),
                new OrientationComponent.Params(true, true, false, false),
                hatchCasing,
                null,
                shape()
        );
    }

    private static ShapeTemplate shape()
    {
        SimpleMember steelCasing = SimpleMember.forBlock(MIBlock.BLOCK_DEFINITIONS.get(MI.id("steel_machine_casing")));
        SimpleMember steelPipe = SimpleMember.forBlock(MIBlock.BLOCK_DEFINITIONS.get(MI.id("steel_machine_casing_pipe")));
        SimpleMember stainlessCasing = SimpleMember.forBlock(MIBlock.BLOCK_DEFINITIONS.get(MI.id("clean_stainless_steel_machine_casing")));
        SimpleMember glass = SimpleMember.forBlockId(ResourceLocation.fromNamespaceAndPath("minecraft", "purple_stained_glass"));

        HatchFlags hatchFlags = new HatchFlags.Builder().with(ITEM_INPUT).with(ITEM_OUTPUT).with(ENERGY_INPUT).build();

        String[][] orgin = new String[][]
                {
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           ccccc           ",
                        "         ccccccccc         ",
                        "        ccccccccccc        ",
                        "        ccccccccccc        ",
                        "       cccccchcccccc       ",
                        "       ccccccccccccc       ",
                        "       ccchcc#cchccc       ",
                        "       ccccccccccccc       ",
                        "       ccccccccccccc       ",
                        "        ccccchccccc        ",
                        "        ccccccccccc        ",
                        "         ccccccccc         ",
                        "           ccccc           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",

                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "         qqcchccqq         ",
                        "        qcccccccccq        ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "      ccccccccccccccc      ",
                        "       ccccccccccccc       ",
                        "       hccccccccccch       ",
                        "       ccccccccccccc       ",
                        "      ccccccccccccccc      ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "        qcccccccccq        ",
                        "         qqcchccqq         ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "         qqcchccqq         ",
                        "        qcccccccccq        ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "     ccccccccccccccccc     ",
                        "       ccccccccccccc       ",
                        "       hccccccccccch       ",
                        "       ccccccccccccc       ",
                        "     ccccccccccccccccc     ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "        qcccccccccq        ",
                        "         qqcchccqq         ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "         qqcchccqq         ",
                        "        qcccccccccq        ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "     ccccccccccccccccc     ",
                        "       ccccccccccccc       ",
                        "       hccccccccccch       ",
                        "       ccccccccccccc       ",
                        "     ccccccccccccccccc     ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "        qcccccccccq        ",
                        "         qqcchccqq         ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "          qqcccqq          ",
                        "         qqcccccqq         ",
                        "        qqqqcccqqqq        ",
                        "       qqqqqcccqqqqq       ",
                        "    cccqcqqqcccqqqcqccc    ",
                        "       cccccqqqccccc       ",
                        "       cccccqqqccccc       ",
                        "       cccccqqqccccc       ",
                        "    cccqcqqqcccqqqcqccc    ",
                        "       qqqqqcccqqqqq       ",
                        "        qqqqcccqqqq        ",
                        "         qqcccccqq         ",
                        "          qqcccqq          ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "         qqqcccqqq         ",
                        "         qqqcccqqq         ",
                        "   ccc   qqqcccqqq   ccc   ",
                        "         cccqqqccc         ",
                        "         cccqqqccc         ",
                        "         cccqqqccc         ",
                        "   ccc   qqqcccqqq   ccc   ",
                        "         qqqcccqqq         ",
                        "         qqqcccqqq         ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "          qqcccqq          ",
                        "   ccc    qqcccqq    ccc   ",
                        "          ccqqqcc          ",
                        "          ccqqqcc          ",
                        "          ccqqqcc          ",
                        "   ccc    qqcccqq    ccc   ",
                        "          qqcccqq          ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "   cc      qcccq      cc   ",
                        "           cqqqc           ",
                        "           cqqqc           ",
                        "           cqqqc           ",
                        "   cc      qcccq      cc   ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "   cc      qcccq      cc   ",
                        "           cqqqc           ",
                        "           cqqqc           ",
                        "           cqqqc           ",
                        "   cc      qcccq      cc   ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "            qqq            ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "   c        qqq        c   ",
                        "  q        q   q        q  ",
                        "  q        q   q        q  ",
                        "  q        q   q        q  ",
                        "   c        qqq        c   ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "            qqq            ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "           ppppp           ",
                        "           q q q           ",
                        "           ppppp           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        " pqp                   pqp ",
                        " p p                   p p ",
                        " pqp                   pqp ",
                        " p p                   p p ",
                        " pqp                   pqp ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           ppppp           ",
                        "           q q p           ",
                        "           ppppp           ",
                        "                           ",
                    },
                    {
                        "            ccc            ",
                        "           p   p           ",
                        "          q  q  q          ",
                        "           p g p           ",
                        "                           ",
                        "             g             ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "  q                     q  ",
                        " p p                   p p ",
                        "c                         c",
                        "c qg g               g gq c",
                        "c                         c",
                        " p p                   p p ",
                        "  q                     q  ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "             g             ",
                        "                           ",
                        "           p g p           ",
                        "          q  q  q          ",
                        "           p   p           ",
                        "            ccc            ",
                    },
                    {
                        "            chc            ",
                        "           p q p           ",
                        "          qqqqqqq          ",
                        "           pgqgp           ",
                        "             q             ",
                        "            gqg            ",
                        "             q             ",
                        "             q             ",
                        "                           ",
                        "                           ",
                        "  q                     q  ",
                        " pqp                   pqp ",
                        "c qg g               g gq c",
                        "hqqqqqqq           qqqqqqqh",
                        "c qg g               g gq c",
                        " pqp                   pqp ",
                        "  q                     q  ",
                        "                           ",
                        "                           ",
                        "             q             ",
                        "             q             ",
                        "            gqg            ",
                        "             q             ",
                        "           pgqgp           ",
                        "          qqqqqqq          ",
                        "           p q p           ",
                        "            chc            ",
                    },
                    {
                        "            ccc            ",
                        "           p   p           ",
                        "          q  q  q          ",
                        "           p g p           ",
                        "                           ",
                        "             g             ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "  q                     q  ",
                        " p p                   p p ",
                        "c                         c",
                        "c qg g               g gq c",
                        "c                         c",
                        " p p                   p p ",
                        "  q                     q  ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "             g             ",
                        "                           ",
                        "           p g p           ",
                        "          q  q  q          ",
                        "           p   p           ",
                        "            ccc            ",
                    },
                    {
                        "                           ",
                        "           ppppp           ",
                        "           q q q           ",
                        "           ppppp           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        " pqp                   pqp ",
                        " p p                   p p ",
                        " pqp                   pqp ",
                        " p p                   p p ",
                        " pqp                   pqp ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           ppppp           ",
                        "           q q p           ",
                        "           ppppp           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "            qqq            ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "   c        qqq        c   ",
                        "  q        q   q        q  ",
                        "  q        q   q        q  ",
                        "  q        q   q        q  ",
                        "   c        qqq        c   ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "            qqq            ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "   cc      qcccq      cc   ",
                        "           cqqqc           ",
                        "           cqqqc           ",
                        "           cqqqc           ",
                        "   cc      qcccq      cc   ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "   cc      qcccq      cc   ",
                        "           cqqqc           ",
                        "           cqqqc           ",
                        "           cqqqc           ",
                        "   cc      qcccq      cc   ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "          qqcccqq          ",
                        "   ccc    qqcccqq    ccc   ",
                        "          ccqqqcc          ",
                        "          ccqqqcc          ",
                        "          ccqqqcc          ",
                        "   ccc    qqcccqq    ccc   ",
                        "          qqcccqq          ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "         qqqcccqqq         ",
                        "         qqqcccqqq         ",
                        "   ccc   qqqcccqqq   ccc   ",
                        "         cccqqqccc         ",
                        "         cccqqqccc         ",
                        "         cccqqqccc         ",
                        "   ccc   qqqcccqqq   ccc   ",
                        "         qqqcccqqq         ",
                        "         qqqcccqqq         ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "          qqcccqq          ",
                        "         qqcccccqq         ",
                        "        qqqqcccqqqq        ",
                        "       qqqqqcccqqqqq       ",
                        "    cccqcqqqcccqqqcqccc    ",
                        "       cccccqqqccccc       ",
                        "       cccccqqqccccc       ",
                        "       cccccqqqccccc       ",
                        "    cccqcqqqcccqqqcqccc    ",
                        "       qqqqqcccqqqqq       ",
                        "        qqqqcccqqqq        ",
                        "         qqcccccqq         ",
                        "          qqcccqq          ",
                        "           c   c           ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "         qqcccccqq         ",
                        "        qcccccccccq        ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "     ccccccccccccccccc     ",
                        "       ccccccccccccc       ",
                        "       ccccccccccccc       ",
                        "       ccccccccccccc       ",
                        "     ccccccccccccccccc     ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "        qcccccccccq        ",
                        "         qqcccccqq         ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "           c   c           ",
                        "         qqcchccqq         ",
                        "        qcccccccccq        ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "      cccccccccccccccc     ",
                        "       ccccccccccccc       ",
                        "       hccccccccccch       ",
                        "       ccccccccccccc       ",
                        "     ccccccccccccccccc     ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "        qcccccccccq        ",
                        "         qqcchccqq         ",
                        "           c   c           ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           c   c           ",
                        "         qqcchccqq         ",
                        "        qcccccccccq        ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "      ccccccccccccccc      ",
                        "       ccccccccccccc       ",
                        "       hccccccccccch       ",
                        "       ccccccccccccc       ",
                        "      ccccccccccccccc      ",
                        "       qcccccccccccq       ",
                        "       qcccccccccccq       ",
                        "        qcccccccccq        ",
                        "         qqcchccqq         ",
                        "           c   c           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                    },
                    {
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "           ccccc           ",
                        "         ccccccccc         ",
                        "        ccccccccccc        ",
                        "        ccccccccccc        ",
                        "       ccccccccccccc       ",
                        "       ccccccccccccc       ",
                        "       ccccccccccccc       ",
                        "       ccccccccccccc       ",
                        "       ccccccccccccc       ",
                        "        ccccccccccc        ",
                        "        ccccccccccc        ",
                        "         ccccccccc         ",
                        "           ccccc           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",
                        "                           ",

                    }
                };

        String[][] fixed = ShapeFixer.transposeLayers(orgin);

        return new ShapeTemplate.LayeredBuilder(MachineCasings.STEEL, fixed)
                .key('c', steelCasing, null)
                .key('p', steelPipe, null)
                .key('q', stainlessCasing, null)
                .key('g', glass, null)
                .key('h', steelCasing, hatchFlags)
                .build();
    }

    @Override
    public MachineRecipeType recipeType() {
        return MIMachineRecipeTypes.ASSEMBLER;
    }

    @Override
    public long getBaseRecipeEu() {
        return 1024;
    }

    @Override
    public long getMaxRecipeEu() {
        return 124000;
    }

    @Override
    protected AnimationSystem createAnimationSystem() {

        Vec3 controllerCenter = this.getBlockPos().getCenter();

        return new BlackHoleCraftingAnim(
                this.level,
                new Vec3(controllerCenter.x,controllerCenter.y + 12, controllerCenter.z),
                1.2f
        );
    }


}
