package gg.amecute.auralithutilities.Multiblock.ShapeTemplate;

import aztech.modern_industrialization.MI;
import aztech.modern_industrialization.MIBlock;
import aztech.modern_industrialization.machines.models.MachineCasings;
import aztech.modern_industrialization.machines.multiblocks.HatchFlags;
import aztech.modern_industrialization.machines.multiblocks.ShapeTemplate;
import aztech.modern_industrialization.machines.multiblocks.SimpleMember;
import gg.amecute.auralithutilities.Utils.ShapeFixer;
import net.minecraft.resources.ResourceLocation;

import static aztech.modern_industrialization.machines.multiblocks.HatchTypes.*;

public class MatterTransformerCrafterShape
{
    private static ShapeTemplate shape;

    public static ShapeTemplate get()
    {
        if(shape != null) return shape;

        SimpleMember steelCasing = SimpleMember.forBlock(MIBlock.BLOCK_DEFINITIONS.get(MI.id("steel_machine_casing")));
        SimpleMember steelPipe = SimpleMember.forBlock(MIBlock.BLOCK_DEFINITIONS.get(MI.id("steel_machine_casing_pipe")));
        SimpleMember stainlessCasing = SimpleMember.forBlock(MIBlock.BLOCK_DEFINITIONS.get(MI.id("clean_stainless_steel_machine_casing")));
        SimpleMember glass = SimpleMember.forBlockId(ResourceLocation.fromNamespaceAndPath("minecraft", "purple_stained_glass"));

        HatchFlags hatchFlags = new HatchFlags.Builder().with(ITEM_INPUT).with(ITEM_OUTPUT).with(ENERGY_INPUT).build();

        String[][] orgin = new String[][]
                {
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           ccccc           ",
                                "         ccccccccc         ",
                                "        ccccccccccc        ",
                                "        ccccccccccc        ",
                                "       cccccchcccccc       ",
                                "       ccccccccccccc       ",
                                "       ccchcc#cchccc       ",
                                "       ccccccccccccc       ",
                                "       ccccccccccccc       ",
                                "        ccccchccccc        ",
                                "        ccccccccccc        ",
                                "         ccccccccc         ",
                                "           ccccc           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",

                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "         qqcchccqq         ",
                                "        qcccccccccq        ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "      ccccccccccccccc      ",
                                "       ccccccccccccc       ",
                                "       hccccccccccch       ",
                                "       ccccccccccccc       ",
                                "      ccccccccccccccc      ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "        qcccccccccq        ",
                                "         qqcchccqq         ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "         qqcchccqq         ",
                                "        qcccccccccq        ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "     ccccccccccccccccc     ",
                                "       ccccccccccccc       ",
                                "       hccccccccccch       ",
                                "       ccccccccccccc       ",
                                "     ccccccccccccccccc     ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "        qcccccccccq        ",
                                "         qqcchccqq         ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "         qqcchccqq         ",
                                "        qcccccccccq        ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "     ccccccccccccccccc     ",
                                "       ccccccccccccc       ",
                                "       hccccccccccch       ",
                                "       ccccccccccccc       ",
                                "     ccccccccccccccccc     ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "        qcccccccccq        ",
                                "         qqcchccqq         ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "          qqcccqq          ",
                                "         qqcccccqq         ",
                                "        qqqqcccqqqq        ",
                                "       qqqqqcccqqqqq       ",
                                "    cccqcqqqcccqqqcqccc    ",
                                "       cccccqqqccccc       ",
                                "       cccccqqqccccc       ",
                                "       cccccqqqccccc       ",
                                "    cccqcqqqcccqqqcqccc    ",
                                "       qqqqqcccqqqqq       ",
                                "        qqqqcccqqqq        ",
                                "         qqcccccqq         ",
                                "          qqcccqq          ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "         qqqcccqqq         ",
                                "         qqqcccqqq         ",
                                "   ccc   qqqcccqqq   ccc   ",
                                "         cccqqqccc         ",
                                "         cccqqqccc         ",
                                "         cccqqqccc         ",
                                "   ccc   qqqcccqqq   ccc   ",
                                "         qqqcccqqq         ",
                                "         qqqcccqqq         ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "          qqcccqq          ",
                                "   ccc    qqcccqq    ccc   ",
                                "          ccqqqcc          ",
                                "          ccqqqcc          ",
                                "          ccqqqcc          ",
                                "   ccc    qqcccqq    ccc   ",
                                "          qqcccqq          ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "   cc      qcccq      cc   ",
                                "           cqqqc           ",
                                "           cqqqc           ",
                                "           cqqqc           ",
                                "   cc      qcccq      cc   ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "   cc      qcccq      cc   ",
                                "           cqqqc           ",
                                "           cqqqc           ",
                                "           cqqqc           ",
                                "   cc      qcccq      cc   ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "            qqq            ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "   c        qqq        c   ",
                                "  q        q   q        q  ",
                                "  q        q   q        q  ",
                                "  q        q   q        q  ",
                                "   c        qqq        c   ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "            qqq            ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "           ppppp           ",
                                "           q q q           ",
                                "           ppppp           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                " pqp                   pqp ",
                                " p p                   p p ",
                                " pqp                   pqp ",
                                " p p                   p p ",
                                " pqp                   pqp ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           ppppp           ",
                                "           q q q           ",
                                "           ppppp           ",
                                "                           ",
                        },
                        {
                                "            ccc            ",
                                "           p   p           ",
                                "          q  q  q          ",
                                "           p g p           ",
                                "                           ",
                                "             g             ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "  q                     q  ",
                                " p p                   p p ",
                                "c                         c",
                                "c qg g               g gq c",
                                "c                         c",
                                " p p                   p p ",
                                "  q                     q  ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "             g             ",
                                "                           ",
                                "           p g p           ",
                                "          q  q  q          ",
                                "           p   p           ",
                                "            ccc            ",
                        },
                        {
                                "            chc            ",
                                "           p q p           ",
                                "          qqqqqqq          ",
                                "           pgqgp           ",
                                "             q             ",
                                "            gqg            ",
                                "             q             ",
                                "             q             ",
                                "                           ",
                                "                           ",
                                "  q                     q  ",
                                " pqp                   pqp ",
                                "c qg g               g gq c",
                                "hqqqqqqq           qqqqqqqh",
                                "c qg g               g gq c",
                                " pqp                   pqp ",
                                "  q                     q  ",
                                "                           ",
                                "                           ",
                                "             q             ",
                                "             q             ",
                                "            gqg            ",
                                "             q             ",
                                "           pgqgp           ",
                                "          qqqqqqq          ",
                                "           p q p           ",
                                "            chc            ",
                        },
                        {
                                "            ccc            ",
                                "           p   p           ",
                                "          q  q  q          ",
                                "           p g p           ",
                                "                           ",
                                "             g             ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "  q                     q  ",
                                " p p                   p p ",
                                "c                         c",
                                "c qg g               g gq c",
                                "c                         c",
                                " p p                   p p ",
                                "  q                     q  ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "             g             ",
                                "                           ",
                                "           p g p           ",
                                "          q  q  q          ",
                                "           p   p           ",
                                "            ccc            ",
                        },
                        {
                                "                           ",
                                "           ppppp           ",
                                "           q q q           ",
                                "           ppppp           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                " pqp                   pqp ",
                                " p p                   p p ",
                                " pqp                   pqp ",
                                " p p                   p p ",
                                " pqp                   pqp ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           ppppp           ",
                                "           q q q           ",
                                "           ppppp           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "            qqq            ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "   c        qqq        c   ",
                                "  q        q   q        q  ",
                                "  q        q   q        q  ",
                                "  q        q   q        q  ",
                                "   c        qqq        c   ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "            qqq            ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "   cc      qcccq      cc   ",
                                "           cqqqc           ",
                                "           cqqqc           ",
                                "           cqqqc           ",
                                "   cc      qcccq      cc   ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "   cc      qcccq      cc   ",
                                "           cqqqc           ",
                                "           cqqqc           ",
                                "           cqqqc           ",
                                "   cc      qcccq      cc   ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "          qqcccqq          ",
                                "   ccc    qqcccqq    ccc   ",
                                "          ccqqqcc          ",
                                "          ccqqqcc          ",
                                "          ccqqqcc          ",
                                "   ccc    qqcccqq    ccc   ",
                                "          qqcccqq          ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "         qqqcccqqq         ",
                                "         qqqcccqqq         ",
                                "   ccc   qqqcccqqq   ccc   ",
                                "         cccqqqccc         ",
                                "         cccqqqccc         ",
                                "         cccqqqccc         ",
                                "   ccc   qqqcccqqq   ccc   ",
                                "         qqqcccqqq         ",
                                "         qqqcccqqq         ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "          qqcccqq          ",
                                "         qqcccccqq         ",
                                "        qqqqcccqqqq        ",
                                "       qqqqqcccqqqqq       ",
                                "    cccqcqqqcccqqqcqccc    ",
                                "       cccccqqqccccc       ",
                                "       cccccqqqccccc       ",
                                "       cccccqqqccccc       ",
                                "    cccqcqqqcccqqqcqccc    ",
                                "       qqqqqcccqqqqq       ",
                                "        qqqqcccqqqq        ",
                                "         qqcccccqq         ",
                                "          qqcccqq          ",
                                "           c   c           ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "         qqcccccqq         ",
                                "        qcccccccccq        ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "     ccccccccccccccccc     ",
                                "       ccccccccccccc       ",
                                "       ccccccccccccc       ",
                                "       ccccccccccccc       ",
                                "     ccccccccccccccccc     ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "        qcccccccccq        ",
                                "         qqcccccqq         ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "           c   c           ",
                                "         qqcchccqq         ",
                                "        qcccccccccq        ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "      cccccccccccccccc     ",
                                "       ccccccccccccc       ",
                                "       hccccccccccch       ",
                                "       ccccccccccccc       ",
                                "     ccccccccccccccccc     ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "        qcccccccccq        ",
                                "         qqcchccqq         ",
                                "           c   c           ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           c   c           ",
                                "         qqcchccqq         ",
                                "        qcccccccccq        ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "      ccccccccccccccc      ",
                                "       ccccccccccccc       ",
                                "       hccccccccccch       ",
                                "       ccccccccccccc       ",
                                "      ccccccccccccccc      ",
                                "       qcccccccccccq       ",
                                "       qcccccccccccq       ",
                                "        qcccccccccq        ",
                                "         qqcchccqq         ",
                                "           c   c           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                        },
                        {
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "           ccccc           ",
                                "         ccccccccc         ",
                                "        ccccccccccc        ",
                                "        ccccccccccc        ",
                                "       ccccccccccccc       ",
                                "       ccccccccccccc       ",
                                "       ccccccccccccc       ",
                                "       ccccccccccccc       ",
                                "       ccccccccccccc       ",
                                "        ccccccccccc        ",
                                "        ccccccccccc        ",
                                "         ccccccccc         ",
                                "           ccccc           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",
                                "                           ",

                        }
                };

        String[][] fixed = ShapeFixer.transposeLayers(orgin);

        shape = new ShapeTemplate.LayeredBuilder(MachineCasings.STEEL, fixed)
                .key('c', steelCasing, null)
                .key('p', steelPipe, null)
                .key('q', stainlessCasing, null)
                .key('g', glass, null)
                .key('h', steelCasing, hatchFlags)
                .build();

        return shape;
    }
}
